# Q
###  1) Prepare a classification model using SVM for salary data (SalaryData_Test(1))

Data Description:

* age -- age of a person
* workclass	-- A work class is a grouping of work 
* education	-- Education of an individuals	
* maritalstatus -- Marital status of an individulas	
* occupation	 -- occupation of an individuals
* relationship -- 	
* race --  Race of an Individual
* sex --  Gender of an Individual
* capitalgain --  profit received from the sale of an investment	
* capitalloss	-- A decrease in the value of a capital asset
* hoursperweek -- number of hours work per week	
* native -- Native of an individual
* Salary -- salary of an individual


###  Import data and models

In [1]:
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn.metrics import accuracy_score, confusion_matrix

In [2]:
data = pd.read_csv('SalaryData_Test(1).csv')
data.head(10)

age          workclass      education  educationno        maritalstatus  \
0   25            Private           11th            7        Never-married   
1   38            Private        HS-grad            9   Married-civ-spouse   
2   28          Local-gov     Assoc-acdm           12   Married-civ-spouse   
3   44            Private   Some-college           10   Married-civ-spouse   
4   34            Private           10th            6        Never-married   
5   63   Self-emp-not-inc    Prof-school           15   Married-civ-spouse   
6   24            Private   Some-college           10        Never-married   
7   55            Private        7th-8th            4   Married-civ-spouse   
8   65            Private        HS-grad            9   Married-civ-spouse   
9   36        Federal-gov      Bachelors           13   Married-civ-spouse   

           occupation    relationship    race      sex  capitalgain  \
0   Machine-op-inspct       Own-child   Black     Male            0   
1     Farming-fishing         Husband   White     Male            0   
2     Protective-serv         Husband   White     Male            0   
3   Machine-op-inspct         Husband   Black     Male         7688   
4       Other-service   Not-in-family   White     Male            0   
5      Prof-specialty         Husband   White     Male         3103   
6       Other-service       Unmarried   White   Female            0   
7        Craft-repair         Husband   White     Male            0   
8   Machine-op-inspct         Husband   White     Male         6418   
9        Adm-clerical         Husband   White     Male            0   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States   <=50K  
1            0            50   United-States   <=50K  
2            0            40   United-States    >50K  
3            0            40   United-States    >50K  
4            0            30   United-States   <=50K  
5            0            32   United-States    >50K  
6            0            40   United-States   <=50K  
7            0            10   United-States   <=50K  
8            0            40   United-States    >50K  
9            0            40   United-States   <=50K

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15060 entries, 0 to 15059
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   age            15060 non-null  int64 
 1   workclass      15060 non-null  object
 2   education      15060 non-null  object
 3   educationno    15060 non-null  int64 
 4   maritalstatus  15060 non-null  object
 5   occupation     15060 non-null  object
 6   relationship   15060 non-null  object
 7   race           15060 non-null  object
 8   sex            15060 non-null  object
 9   capitalgain    15060 non-null  int64 
 10  capitalloss    15060 non-null  int64 
 11  hoursperweek   15060 non-null  int64 
 12  native         15060 non-null  object
 13  Salary         15060 non-null  object
dtypes: int64(5), object(9)
memory usage: 1.6+ MB


In [4]:
data['workclass'] = data['workclass'].astype('category')
data['education'] = data['education'].astype('category')
data['maritalstatus'] = data['maritalstatus'].astype('category')
data['occupation'] = data['occupation'].astype('category')
data['relationship'] = data['relationship'].astype('category')
data['race'] = data['race'].astype('category')
data['sex'] = data['sex'].astype('category')
data['native'] = data['native'].astype('category')
data['Salary'] = data['Salary'].astype('category')

In [5]:
data.dtypes

age                 int64
workclass        category
education        category
educationno         int64
maritalstatus    category
occupation       category
relationship     category
race             category
sex              category
capitalgain         int64
capitalloss         int64
hoursperweek        int64
native           category
Salary           category
dtype: object

In [6]:
data['Salary'] = data['Salary'].cat.codes
data.head()

age   workclass      education  educationno        maritalstatus  \
0   25     Private           11th            7        Never-married   
1   38     Private        HS-grad            9   Married-civ-spouse   
2   28   Local-gov     Assoc-acdm           12   Married-civ-spouse   
3   44     Private   Some-college           10   Married-civ-spouse   
4   34     Private           10th            6        Never-married   

           occupation    relationship    race    sex  capitalgain  \
0   Machine-op-inspct       Own-child   Black   Male            0   
1     Farming-fishing         Husband   White   Male            0   
2     Protective-serv         Husband   White   Male            0   
3   Machine-op-inspct         Husband   Black   Male         7688   
4       Other-service   Not-in-family   White   Male            0   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States       0  
1            0            50   United-States       0  
2            0            40   United-States       1  
3            0            40   United-States       1  
4            0            30   United-States       0

###  will use the age and hoursperweek only for this analysis

In [7]:
data1 = data.iloc[:,[0,11,13]]
data1.head()

age  hoursperweek  Salary
0   25            40       0
1   38            50       0
2   28            40       1
3   44            40       1
4   34            30       0

In [8]:
x = data1.iloc[:,0:2]

In [9]:
print(x)

       age  hoursperweek
0       25            40
1       38            50
2       28            40
3       44            40
4       34            30
...    ...           ...
15055   33            40
15056   39            36
15057   38            50
15058   44            40
15059   35            60

[15060 rows x 2 columns]


In [10]:
y = data1.iloc[:,-1]
print(y.head())

0    0
1    0
2    1
3    1
4    0
Name: Salary, dtype: int8


###  print the unique labels of the dataset

In [11]:
np.unique(y)

array([0, 1], dtype=int8)

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = .3,random_state = 0)

In [14]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((10542, 2), (10542,), (4518, 2), (4518,))

In [15]:
from sklearn.svm import SVC

In [16]:
svm = SVC(kernel = 'rbf', gamma = .10, C = 1.0)

In [17]:
svm.fit(x_train,y_train)

SVC(gamma=0.1)

###  The accuracy of the sum classifire on the training data 

In [18]:
svm.score(x_train,y_train)

0.7705369000189717

###  The accuracy of the classifire on the test data

In [19]:
svm.score(x_test,y_test)

0.7532093846834883

In [50]:
clf = SVC(C= 1.5, gamma = .50)
clf.fit(x_train , y_train)
y_pred = clf.predict(x_test)
acc = accuracy_score(y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred)

Accuracy = 74.9003984063745


array([[3192,  193],
       [ 941,  192]], dtype=int64)

# Q
### 2) Prepare a classification model using SVM for salary data (SalaryData_Train(2))
Data Description:

* age -- age of a person
* workclass -- A work class is a grouping of work
* education -- Education of an individuals
* maritalstatus -- Marital status of an individulas
* occupation -- occupation of an individuals
* relationship --
* race -- Race of an Individual
* sex -- Gender of an Individual
* capitalgain -- profit received from the sale of an investment
* capitalloss -- A decrease in the value of a capital asset
* hoursperweek -- number of hours work per week
* native -- Native of an individual
* Salary -- salary of an individual

In [21]:
data2 = pd.read_csv('SalaryData_Train(1).csv')

In [22]:
data2.head()

age          workclass   education  educationno        maritalstatus  \
0   39          State-gov   Bachelors           13        Never-married   
1   50   Self-emp-not-inc   Bachelors           13   Married-civ-spouse   
2   38            Private     HS-grad            9             Divorced   
3   53            Private        11th            7   Married-civ-spouse   
4   28            Private   Bachelors           13   Married-civ-spouse   

           occupation    relationship    race      sex  capitalgain  \
0        Adm-clerical   Not-in-family   White     Male         2174   
1     Exec-managerial         Husband   White     Male            0   
2   Handlers-cleaners   Not-in-family   White     Male            0   
3   Handlers-cleaners         Husband   Black     Male            0   
4      Prof-specialty            Wife   Black   Female            0   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States   <=50K  
1            0            13   United-States   <=50K  
2            0            40   United-States   <=50K  
3            0            40   United-States   <=50K  
4            0            40            Cuba   <=50K

In [23]:
data2.dtypes

age               int64
workclass        object
education        object
educationno       int64
maritalstatus    object
occupation       object
relationship     object
race             object
sex              object
capitalgain       int64
capitalloss       int64
hoursperweek      int64
native           object
Salary           object
dtype: object

In [25]:
data2['workclass'] = data2['workclass'].astype('category')
data2['education'] = data2['education'].astype('category')
data2['maritalstatus'] = data2['maritalstatus'].astype('category')
data2['occupation'] = data2['occupation'].astype('category')
data2['relationship'] = data2['relationship'].astype('category')
data2['race'] = data2['race'].astype('category')
data2['sex'] = data2['sex'].astype('category')
data2['native'] = data2['native'].astype('category')
data2['Salary'] = data2['Salary'].astype('category')

In [26]:
data2['Salary'] = data2['Salary'].cat.codes

In [27]:
data3 = data2.iloc[:,[0,11,13]]

In [28]:
data3.head()

age  hoursperweek  Salary
0   39            40       0
1   50            13       0
2   38            40       0
3   53            40       0
4   28            40       0

In [34]:
X = data3.iloc[:,0:2]
Y = data3.iloc[:,2]

In [35]:
print(X.head())

   age  hoursperweek
0   39            40
1   50            13
2   38            40
3   53            40
4   28            40


In [36]:
print(Y.head())

0    0
1    0
2    0
3    0
4    0
Name: Salary, dtype: int8


In [37]:
from sklearn.model_selection import train_test_split

In [42]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = .4, random_state= 0)

In [43]:
X_train.shape, Y_train.shape, X_test.shape, Y_test.shape

((18096, 2), (18096,), (12065, 2), (12065,))

###  SVC

In [44]:
cv = SVC(kernel = 'rbf', random_state = 0, gamma = .10, C = 1.0 )

In [45]:
cv.fit(X_train,Y_train)

SVC(gamma=0.1, random_state=0)

###  The accuracy of the sum classifire on the training data

In [46]:
cv.score(x_train,y_train)

0.7557389489660405

### The accuracy of the classifire on the test data

In [47]:
cv.score(x_test,y_test)

0.7565294378043382

In [49]:
clf = SVC(C= 1.5, gamma = .15)
clf.fit(X_train , Y_train)
Y_pred = clf.predict(X_test)
acc = accuracy_score(Y_test, Y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(Y_test, Y_pred)

Accuracy = 76.14587650227932


array([[8549,  512],
       [2366,  638]], dtype=int64)

# Q
###  classify the Size_Categorie using SVM

* month	month of the year: 'jan' to 'dec'
* day	day of the week: 'mon' to 'sun'
* FFMC	FFMC index from the FWI system: 18.7 to 96.20
* DMC	DMC index from the FWI system: 1.1 to 291.3
* DC	DC index from the FWI system: 7.9 to 860.6
* ISI	ISI index from the FWI system: 0.0 to 56.10
* temp	temperature in Celsius degrees: 2.2 to 33.30
* RH	relative humidity in %: 15.0 to 100
* wind	wind speed in km/h: 0.40 to 9.40
* rain	outside rain in mm/m2 : 0.0 to 6.4
* Size_Categorie 	the burned area of the forest ( Small , Large)

In [51]:
size = pd.read_csv('forestfires.csv')

In [53]:
size.head(10)

month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  ...  monthfeb  \
0   mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0  ...         0   
1   oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0  ...         0   
2   oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0  ...         0   
3   mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2  ...         0   
4   mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0  ...         0   
5   aug  sun  92.3   85.3  488.0  14.7  22.2  29   5.4   0.0  ...         0   
6   aug  mon  92.3   88.9  495.6   8.5  24.1  27   3.1   0.0  ...         0   
7   aug  mon  91.5  145.4  608.2  10.7   8.0  86   2.2   0.0  ...         0   
8   sep  tue  91.0  129.5  692.6   7.0  13.1  63   5.4   0.0  ...         0   
9   sep  sat  92.5   88.0  698.6   7.1  22.8  40   4.0   0.0  ...         0   

   monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  monthoct  \
0         0         0         0         1         0         0         0   
1         0         0         0         0         0         0         1   
2         0         0         0         0         0         0         1   
3         0         0         0         1         0         0         0   
4         0         0         0         1         0         0         0   
5         0         0         0         0         0         0         0   
6         0         0         0         0         0         0         0   
7         0         0         0         0         0         0         0   
8         0         0         0         0         0         0         0   
9         0         0         0         0         0         0         0   

   monthsep  size_category  
0         0          small  
1         0          small  
2         0          small  
3         0          small  
4         0          small  
5         0          small  
6         0          small  
7         0          small  
8         1          small  
9         1          small  

[10 rows x 31 columns]

In [54]:
size.dtypes

month             object
day               object
FFMC             float64
DMC              float64
DC               float64
ISI              float64
temp             float64
RH                 int64
wind             float64
rain             float64
area             float64
dayfri             int64
daymon             int64
daysat             int64
daysun             int64
daythu             int64
daytue             int64
daywed             int64
monthapr           int64
monthaug           int64
monthdec           int64
monthfeb           int64
monthjan           int64
monthjul           int64
monthjun           int64
monthmar           int64
monthmay           int64
monthnov           int64
monthoct           int64
monthsep           int64
size_category     object
dtype: object

In [55]:
size['size_category'] = size['size_category'].astype ('category')

In [56]:
size['size_category'] = size['size_category'].cat.codes

In [59]:
size1 = size.iloc[:,2:]

In [60]:
size1.head()

FFMC   DMC     DC  ISI  temp  RH  wind  rain  area  dayfri  ...  monthfeb  \
0  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0       1  ...         0   
1  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0       0  ...         0   
2  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0       0  ...         0   
3  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0       1  ...         0   
4  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0       0  ...         0   

   monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  monthoct  \
0         0         0         0         1         0         0         0   
1         0         0         0         0         0         0         1   
2         0         0         0         0         0         0         1   
3         0         0         0         1         0         0         0   
4         0         0         0         1         0         0         0   

   monthsep  size_category  
0         0              1  
1         0              1  
2         0              1  
3         0              1  
4         0              1  

[5 rows x 29 columns]

In [76]:
size.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 31 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   month          517 non-null    object 
 1   day            517 non-null    object 
 2   FFMC           517 non-null    float64
 3   DMC            517 non-null    float64
 4   DC             517 non-null    float64
 5   ISI            517 non-null    float64
 6   temp           517 non-null    float64
 7   RH             517 non-null    int64  
 8   wind           517 non-null    float64
 9   rain           517 non-null    float64
 10  area           517 non-null    float64
 11  dayfri         517 non-null    int64  
 12  daymon         517 non-null    int64  
 13  daysat         517 non-null    int64  
 14  daysun         517 non-null    int64  
 15  daythu         517 non-null    int64  
 16  daytue         517 non-null    int64  
 17  daywed         517 non-null    int64  
 18  monthapr  

In [67]:
size2= size1.values
size2

array([[ 86.2,  26.2,  94.3, ...,   0. ,   0. ,   1. ],
       [ 90.6,  35.4, 669.1, ...,   1. ,   0. ,   1. ],
       [ 90.6,  43.7, 686.9, ...,   1. ,   0. ,   1. ],
       ...,
       [ 81.6,  56.7, 665.6, ...,   0. ,   0. ,   0. ],
       [ 94.4, 146. , 614.7, ...,   0. ,   0. ,   1. ],
       [ 79.5,   3. , 106.7, ...,   0. ,   0. ,   1. ]])

In [70]:
x = size2[:,0:-1]
x

array([[ 86.2,  26.2,  94.3, ...,   0. ,   0. ,   0. ],
       [ 90.6,  35.4, 669.1, ...,   0. ,   1. ,   0. ],
       [ 90.6,  43.7, 686.9, ...,   0. ,   1. ,   0. ],
       ...,
       [ 81.6,  56.7, 665.6, ...,   0. ,   0. ,   0. ],
       [ 94.4, 146. , 614.7, ...,   0. ,   0. ,   0. ],
       [ 79.5,   3. , 106.7, ...,   1. ,   0. ,   0. ]])

In [72]:
y = size2[:,-1]
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [119]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = .4,random_state =10)

In [120]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((310, 28), (310,), (207, 28), (207,))

In [121]:
ss = SVC(kernel = 'rbf', random_state = 10, gamma = 150, C = 55)

In [122]:
ss.fit(x_train,y_train)

SVC(C=55, gamma=150, random_state=10)

###  The accuracy of the ss classifier on the training data 

In [123]:
ss.score(x_train,y_train)*100

100.0

###  The accuracy of the classifire on the test data 

In [124]:
ss.score(x_test,y_test)*100

72.46376811594203

In [127]:
clf = SVC(C= 15, gamma = 150)
clf.fit(x_train , y_train)
y_pred = clf.predict(x_test)
acc = accuracy_score(y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred)

Accuracy = 72.46376811594203


array([[  1,  57],
       [  0, 149]], dtype=int64)